apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blog-dev

resources:
  - namespace.yaml
  - ../../base/postgres
  - ../../base/blog-api
  - blog-api-ingress.yaml
  - ../../base/blog-ui
  - blog-ui-ingress.yaml
  - ../../base/blog-agent
  - networkpolicy-postgres.yaml

patches:
  - path: deployment-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: blog-api
  - path: blog-ui-service-patch.yaml
    target:
      version: v1
      kind: Service
      name: blog-ui
  - path: blog-api-service-patch.yaml
    target:
      version: v1
      kind: Service
      name: blog-api
  - path: blog-agent-configmap-patch.yaml
    target:
      version: v1
      kind: ConfigMap
      name: blog-agent-config
  - path: postgres-service-patch.yaml
    target:
      version: v1
      kind: Service
      name: postgres
