apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
- namespace.yaml
- ../../base/postgres
- ../../base/blog-api
- ../../base/blog-ui
- ../../base/monitoring

patchesStrategicMerge:
    - ingress-patch.yaml

labels:
- pairs:
    environment: dev
