apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-ui
  annotations:
    # Restrict to local network and VPN only
    nginx.ingress.kubernetes.io/whitelist-source-range: "192.168.50.0/24"
