apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: petedillo-dev
  namespace: argocd
spec:
  description: PeteDillo.com development environment

  sourceRepos:
  - 'https://github.com/petedillo/blog-gitops'

  destinations:
  - namespace: dev
    server: https://kubernetes.default.svc
  - namespace: argocd
    server: https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: ''
    kind: Namespace

  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'

  orphanedResources:
    warn: true
