apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-api
spec:
  template:
    spec:
      containers:
      - name: blog-api
        env:
        - name: APP_ENVIRONMENT
          value: "stage"
        - name: SPRING_PROFILES_ACTIVE
          value: "stage"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: JWT_SECRET
        - name: OAUTH_GOOGLE_ENABLED
          value: "false"
        - name: OAUTH_APPLE_ENABLED
          value: "false"
      volumes:
      - name: media-storage
        persistentVolumeClaim:
          claimName: blog-media-pvc-stage
