apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blog-stage

resources:
- namespace.yaml
- ../../base/postgres
- ../../base/blog-api
- ../../base/blog-ui
- ../../base/monitoring
- networkpolicy-postgres.yaml
- sealed-secrets/postgres-credentials.yaml
- sealed-secrets/blog-app-credentials.yaml
- sealed-secrets/jwt-secret.yaml
- sealed-secrets/cloudflare-cert.yaml
- sealed-secrets/nexus-registry.yaml
- media-pv-stage.yaml
- media-pvc-stage.yaml

patches:
  - path: ingress-patch.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: blog-api
  - path: ui-ingress-patch.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: blog-ui
  - path: api-deployment-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: blog-api
  - path: postgres-deployment-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: postgres
  - path: prometheus-rules-patch.yaml
    target:
      group: monitoring.coreos.com
      version: v1
      kind: PrometheusRule
      name: blog-alerts
  - path: grafana-ingress-patch.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: grafana

labels:
- pairs:
    environment: stage
