apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  template:
    spec:
      containers:
      - name: postgres
        env:
        - name: BLOG_APP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: admin-credentials
              key: ADMIN_PASSWORD