apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: blog-alerts
spec:
  groups:
  - name: infrastructure.rules
    rules:
    - alert: HighMemoryUsage
      expr: |
        (container_memory_usage_bytes{namespace="blog-stage"} / container_spec_memory_limit_bytes{namespace="blog-stage"}) > 0.9
    - alert: PodCrashLooping
      expr: |
        rate(kube_pod_container_status_restarts_total{namespace="blog-stage"}[15m]) > 0.1
    - alert: HighDatabaseConnections
      expr: |
        pg_stat_activity_count{namespace="blog-stage"} > 90