apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  log.level: info
  registries.conf: |
    registries:
      - name: Nexus Docker Registry
        prefix: docker.toastedbytes.com
        api_url: https://docker.toastedbytes.com
        credentials: secret:argocd/nexus-registry-creds#creds
        default: true
