---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nexus-registry-creds
  namespace: argocd
spec:
  encryptedData:
    creds: AgBo5sV+uBL4sxoeabcQlu3m01V2MQIs+HNAVDhF//WaUjVGmREB8at4NTnmkRDUImykJ534mbm5/bGfI4yKIfwhem47F7NvQnsjrX1yC3lsRMaU4g2gF7LVsMHyEwKMNoQqc+qt6SFQxuyqV0zCBid3vI5hCqKLztGcS7SH7Bpae7s8inMgs67C8+nwuvnaGrA3r2zZ9pkEkq2I8S9IeFg0xW/9ioFt+lq1sfJwrndnYYrYwIZkCOEqUNl15XdmKRDvwRfEDfOp6fy04fsQiVEaL5lSnzVVdIlIU+2m3depgxb776dYL629KxwQTU6sbMfn5BWQvcCjbnGyfoXh2pA6m7YZUbWiSXiar6UQfRvuZZTV3/FzA6TexBBfVUZ0k1w4uY/43kjXj+b/P7PIKT9mjXsNEMaIrEWsklTK4rH1ZyafaS98dE7jMw26rfU7BZ1jsL/+HFftzkIwu/ZKKE4F5r6jRuJCos8LGd6hia4RN9U6OBWZzsUglplYjwSDEKY6rYN5UNnpWwlGpnZyR7+4PXgRi3J2ZcxlL/4HjLewyaVF6kS7cvFIAm8xnY1C07VN10stcy1GypWu5ELKpsm2iI+zKoc8TWmt00Zi/q2mEQl8AWmeM0am4pUWMGWM7GjVYD0pBNdX5KTW2rdXAK80/Z3khOnN6gFeBRifJDNplXuD2ygQrNGd+SZpMRg6IkDy+J7cfcQAxtaxuKpt2H3Kw2jPVlrLbSzSy6cWAGjbkSm/vOsMt7+24w==
  template:
    metadata:
      name: nexus-registry-creds
      namespace: argocd
