---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nexus-registry-creds
  namespace: argocd
spec:
  encryptedData:
    creds: AgCWITSZRuYV6jMnu0BoaxRGK9Y0Y8WppAbazXAOwnGXOg5dssFjHwjmzxXXJpBwGu6EhVbFshwTAdYEo+88ni5Gh+QJiUkdb0UQpYjEmq9KEPkFyDX96bzHWCmnS2VKXz9j4v98NM7bYIgE8t0oGkMuZKGGlIJJOAYTNhz/SBibNU56MeXBxTAkadxybAl0maW1vMMLXA0K8C+r5AKhgi31zhpRwC89oijWTydlts/XlzU/tvy2Mw34vprQMF9obdrJvNqoNAeU9M2yM3OhMH6S42tfs7MmNNVjj1G9JhtNaNRjB7764Yt8b6SoV11ede49myw1OXqvq6biijQRfl8vewXzwGjObHmjxJLwr0JhgI+mQJUl34bIkk3aGSTe0n/tE/uRJKM3qb3Zn64YY1/WBitDvrnxn/RLYSHhFa62/E6Wjjh/ZMxCUsD5d1B0s0fRDfrccQc+G1PbhC5nFl3usHcck+z1f/yuDM2IaLs7AVZIYgAboHyxLAyO6j56yqQzw15Qnz6PEbBEoKnozspdAf9sSo3iHQV3voxd51PENWkEoO3NAVm/0qkGLlT3Q1WsAROZwKWFnbUzKSSObVrl+Qxs2d5spX65IhWgBfUE+mah13Gm6VwDfgs5xUxVBYGbeKpka9fkPp8+ExsRXK6xAdEnWTrNhCrf4muP2Ezh9kvi+K2zLXWkQm1AcOx2NVZ0Cu8R2TZC0Zp127W2ca4HQgSxbPo=
  template:
    metadata:
      name: nexus-registry-creds
      namespace: argocd
