config:
  registries:
    - name: Nexus Docker Registry
      prefix: docker.pdlab.dev
      api_url: https://docker.pdlab.dev
      credentials: secret:argocd/nexus-registry-creds#creds
      default: true

  logLevel: info
