---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: admin-credentials
  namespace: blog-dev
spec:
  encryptedData:
    ADMIN_PASSWORD: AgBOENLFS8wEH4ybV84nV44ixNRqV1gBpAdtD4ED7mNibYZXtFT02AtaQ1xcSPvKcAPSFBDczpYDW6x+4FLPxvDhn7gMar0Ocvi0M+doNLsXaRVKODLjNwImzEYTLRzRYrhKKhtTVryMkZqCbQxksriKh/24Au4uo3FaP1AOtfC1mbgVzMQ1BA56A6IQe1AFah6CSwEYIfDNhBq9GmIxNszOQV/syYpehitvX7fhFEOq4RprLYtbe8UogKthB4X/3GGPA3QlTuE3INO+iejLmdtHmWRuLlCKYnANlSNFq+HeRN1Tvs5pKZwF3R6bEwSSbBOOU8/B+yJMc+RGLtsdxPnAHFNVhnK2Zw4pYAl6Vphrv9ecJSN+sae9NeCv8Y1e1a4tDyaxoNmQKNEiX9BqPK5pcokxUtPMDZKsreDtc7+f97oq5uCE1FXTgLIAzP3v5yCQADPWnt3y+CGS5UodvEyopmiUmzc4HPXfls/pjsyuluGp0bNbYOvnTp5q+e7lZWe2VEYUXWLxj3mYLnd83YCYOeOYK1qHdwOWvg08GvFIImsupzlKF5uo8AfYdqPItYys3A4i7+ST0ucdhCZX/f9k2h8e1+Di/B6kpuXShGgHd1SL/p/Q+OG+uRk/EPtxlzJAH9sVBWwZRbsS3lw8qGkabQEsFf43d1IUF+qWXLkmirfFQcMGW+VGX3FAIZpVjjIbLJ+s6BH8M2iAthMpNWVRE3OyhiOKSz6MF1NK65mE2A==
    ADMIN_USERNAME: AgAqmxWVW7VQrzN3kHh/Vm2y8zOe0WAm2s2nBtHOQJruUslJKgelXznXY27eldekUEtqodK0rAvLYYYdmK0rgmJBTyfZ+keVJGIsl4/S8gQIvGuHEBeAqIGs3a3ws4JoU3bzr/RJKongcwkgIhMnA9AiXwabSeO7k3SBI9R/f+nqH29VRfvw2b3weMEHXnhbnDXtFLxHHJCzRqZetodKAhPB9wu86B5Iz2uurd5XwJsftrSVHb8fyuJRMBjul3VMLtne84Ck4nBNc8e1+UB3rUChGhwglZP01ypYg/Ajt9A9nKFGQ2CUkL823Jk/CX3VIv02HZb6XLfCdQYtHi69qHRfL794y9Cgi1CEBmbvQy31Qqq4fLqhKmahlDx5TqZgIfk5F0zJXj1sV/DpORH/erUIPbWJVLpVmilmS8vj455HoxNr73jex9XcF6rY3q62mYtvmqavzMV6cjgWfrTNoYGaboyS4YFX8OLSulHIHgERHku7enJL6XpifOCHBEvTArgHMrgtvL5sd864AwOTwz1StRFjKmun0YDpTmxb89rP3HsWNzM7Q3su/5SY10Gzy8ZDX2VbJOw7abQACsy4cW2bGpvPuEh0AXbMjtCdd1JgSHz7s8YA/Qb1Up2utniXXJbBLcEU9uDbAlgWheYPM6ku4x8nEoLKhcJbh1jRtEnHHB0WJvt467rKtBv5/2KjRXdzDflX5A==
  template:
    metadata:
      name: admin-credentials
      namespace: blog-dev
