---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: blog-app-credentials
  namespace: blog-dev
spec:
  encryptedData:
    password: AgAOrDWeWRD0flbNLbYZrW8E8TfZpP/dWRZ7KYUWeJ5fNz91W0WNeIiaA7pl0YvkQJWckm60NzjLv7sHP+qV+gVHGMSDJcwxlbrfc1ivg2aziNOR9g26BC1OS0DItzv+RJhmUPShY3jTGUGibU4GjfrLhxZvpxtjva6+eK2heMMqPrHBYP6KfByslhC+9c3CwWEnqt2gxDyDVFiCbhecGG5mcYE2fKA4nkE1Gv6iVl+Cn2xdJ4rVW5wqehdWuJCkv9YifhrATHeG8BVF45Kn2aGE7oLifJ6FPrMpm3yQsWB/jRvnjSQlyL5xlZi+xEcIK22YY+Z+rPWaIhfRfWtEjatB4hMwP+7sQtB9Pg+FHJ0L5c4A0/INZp94N/N0FQVQWygPvzZXzQvN15wULzdX5N6LcrKIuXGFAPKIbVR+Em76VcMwFDlZsIkUPaL1zvtrhB49kSp2ZrJK7w7lzV++5Quk5wG7s19kIPHS6Zbl670Nn39H5F1MsFD5xSODYo8DeVSmPnoDv4eRyAkGm2K4kKwfKGXXGr7s7o/KzkUJw+LWfIT6OT7gU7Is0Uu8IzH2dRdSMKEBi43bG14X/nv1STQdyKWN7j3Yp+3OcEdudEF/VaHSwXXmqxYFVA6OJSOuaN2vLHBCwL1jEHbVQjZljoll5bTsiibkg3xsqlFySe93S1UkT9u+MQNty3oQh5Ot0oQ/J1U7r+K5AcwtNxdwQ4bJ1tBklPSxMIIkelzc78eqZw==
  template:
    metadata:
      name: blog-app-credentials
      namespace: blog-dev
