---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-secret
  namespace: blog-dev
spec:
  encryptedData:
    JWT_SECRET: AgCBd5OrykCx5kT9S21zArD46Vq+vH0Vkevi5W1lgs7rbZtbAGAylDyov3O0EJDfxQJhsoo2G71OBhWoor2IDMazesQsx4vzGKp/86mxd1bTxq7fD6Fw1e2QFNGoNugIn5mAKTYTnLRj6on1Yyoq9wQcNih5C8i57NN8CAtBJZ0IqM704bl7fg98ZN1SsuJJNEBo4JLfonhhSzk/uEtYJyP+cxeELSyVzhtBl27rqfDUYNnumhrhs0lMrOnF1rPbp1wJYZJr73Vk1CNPBfmfL67VvBtSl2SlurUlNw0o0mgDDOJmmRutcvMoJyuq/eP3djh3h0huDjNpcCBzJvxTGbgVAtGL7eZCEJr5eoJ24sP3cGhmgLkYwt1+AtO/0Z5q/efeodIbbZ1TnS9MfGKehCQD72UR/TRu47X1a8SHRRuqhZPG/VY2vGyWU5ZI4KqS/EzaXpvxA45iXWCyaS+sdSA67Fp2aLv05t/n6SFsq6u/FVPs5XDP5ubuZNIy7VIhU28MZ5RXAqcKWMI90YTPxcfH62Zh1TRE0K96u/Mnml874XYMArKhssjiQMKe9hmhpaNusg+bTA+YM+bZYp5e1b8cyP3v473uzr0eVM32gz7qVzd5w+1Qp9r4dAnbKaDASlm+UfER2Xc860/Hy1PWaIL1IAeTq4FOri9AWan6teqkH/x3bE+iTnStOrJd+PPvnAeO9vvudFNxLv8NVQyoxanzVjw/yvegesvGqrOwS+qnNWuexa55E0ofJ935/TtMGFGP6owXtK6fxby0MOqzhVSQ
  template:
    metadata:
      name: jwt-secret
      namespace: blog-dev
