---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nexus-registry
  namespace: blog-dev
spec:
  encryptedData:
    .dockerconfigjson: AgA7AXDQlK4Iv2NRFi+W3hTuxUnk23vdFmxxp6oG3zx3nfeTw3ILfhQFXgkb9/z5qtRZeUMwZYLTi8eZmwsM/TkRcNU6LfHh2LPW25Ig0gQmNNtuPLtdkN6NuPo8X++NlYEC36RQP/3XXRsxsMrlnDXp96RbM4/vzDge827WRDszPisc4MhtUDzR07rawZCUUMgRLzUQQjSXM1JavI3FW+XDSNO7Pkae6G7tYde6zDQpn0jh16nU7oh9clma7uShR6HNg6BT6f+SgcwoVd36adbeM1PUWB6CbJwM7m1Acm8Cq7vcr2qdBM4iuVMz6Tfzh/mpoLyvw3vIGY8HKt90njIAtvC6wOeIvcFM9Esj0CKkgKiccMFB2DfNlGrPqeIiA1Wlv66bkYJM6AIz3wvTXmDguuiyb9TwirWLERpbvX+kxjvoSSUtxbnsW7OO3zvRejZZ03SrAR8tPHl2EvYFkS/5NzZVWbykMecTpggbNpUbb5l01eIcmDnv57ygvQtiI4HG72MHr18KW8wD2aLLXPOrtFrZLnFWlp2NJZZ/el3UBpud2wD1gr/qnG0cXaxwt4ov+hX8LQVFGOGyMVBNCKhlJpEUKDaCzIcMpemu+cCXwbtKPI6Z9JAUEnt0FUsMa1O5WWBgDUFfu1m6rLCY9g+KOTFdYrP0UK0LA7TYpQIg0KmcLalflGcjCq/8qcTUCOabKNJSGordoa6opJdw1Mz9M/oCyQZocirPDyCybv7Rt4BphOt8ntCQZUD0DXt+6npYfwxl+38l4ARR7cvlGa0tSasv8KDiaRb7BnXfBSirCstGol6Aogwa868MeYOWP/NVnQO3F35tXoT37Sxq3uZCl0NltW8EdLGioj/h/MGmOxDbYuVPINvY1b7SsVdpp1SIcKeFDpoTctz8jVv5yA==
  template:
    metadata:
      name: nexus-registry
      namespace: blog-dev
    type: kubernetes.io/dockerconfigjson
