---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: blog-dev
spec:
  encryptedData:
    password: AgCyHtEt5v4aLZdxXrhJtyc659HpOwFtEAj2ejb227eR6zNyZ8eYKvl+3SZqHKvR8Qq3gFcxLd8Y1XbuIHyHaYww1xNk0dZBhrPUfGzVs1h93zcnvacEZrAvW4/DXa2+gzDa738r2L4hcCnKsYY9Q9iD+aJ8e+lX3l3nJoKzP2isi74L6oleR9DI2WEAMaqdGG47YUmssWWG3x2fM7L5AdW+djT/+CJFu43vVFnMSzlwUR9xVqvNRVvOFH9zJKhTv21fXwCMxDOAPgR8EDN3Jb/8A1d57qv3vyRnY5kw7p/cqtIdWLf6xgGlYFzibdnKLfyrvQ2Qr05Do+XL+LQo6L4tHZIGDMS1//5Uy+LOJYqJhKKhWqFlxAUQ6l3npyH1actAOR4afGARvZEAJKRzlHIrqMhbCHnnW8bjEkktcSPNDXI0jgKrDo/x4BpegkKivXkUjMCcZCeY8Dodaedi5Oc0UMDQuJuxdmnK97G0ZlAAbSWBizv0xiSAWssB9R2N5QR3FXIlNNdG0FCbJrvUBgm2iNZq5VTAIwZEdCtDs9Iy1m8wkOvYL1HfS49TSuLkdCDPULW9/vbZ6wPf3goT9W3YvzQPgNQW0Du6Q/I6CITSAYoTI45rJcKt4VhWX+ds++VfLgdSvyjjJ/RAgfhyy1gEbQPHKupYDKAw2FOEx1hkiRiYnOYRiTNKgFQ8NNH8Gr79uvLrSTwEmRfn7CjybR3xPmtKYL9IPJkXlhlNvABqvAzfUNwjB5Ri1BMLhg==
  template:
    metadata:
      name: postgres-credentials
      namespace: blog-dev
