---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: blog-dev
spec:
  encryptedData:
    password: AgCZugUshgJebfNHJ36ax6lErKqf2aQ6V6d/VUdoEbhciycMJMsNPlgz0SYNdHLzd4u5XPFWjsi/p60s51EXk/BtThfLXsXVk9nsab4Tx08QKUALNycN5NH5M1H/zbbvCWeGqEv+IGQEQb4g+AT2SUqzlad1XjKP++Jbhshm7OMkWAFMRHeNLeJ/myHrxDo10IY0GBFybflyIBtx+7MXySkT91bNb8zGKRBwCaVdGISh+OwRtEa/JtmdPz/yjq/9sLpHrIqil9psWWxIX6eS9PNX33YE2lEoHlcYzn/h15iIa/Xme3NhywKr79toZDMlJHikf6w7EDXkTaDg/Jly+u+oud/Hx0ZZOJ4g3Epm5D8brh9G4aEK3+QvjDZ0WW18+G2BTXey/CwoGOl/kEhEa1vHg9wD7SOLal0GntYB6zE9+rIs64U0I9RQnTTZ1tXjTUWPBfrtBr5J85Yus+yH9p1Jl4Y61cJ0lW7p9a/A8dAAcR6IjUo0nhInGQJINSJ4Xaula6cw0pSL/WHw2FmmCUXC3m76oUhJD+7uBAFBZCh+taU9KvrqFgq3taEG7LpQsLtf2jFtBPu9cHYADT2o6dp+/F6aeXC/0I4OZnt0WpjifRauzpinM4KlZCed1wurOgrpuatT0Ls4DtKhqhdV7xlCmtzFrfrUHjA87xnvz8cTMONRGDLcj9kIKVGIr6tMIFqKBZT9MCP8FtR/VnxFiC3LXni0StxWCxZ/oA/KCTVnR2oyAmxxDY6YeQlY+w==
  template:
    metadata:
      name: postgres-credentials
      namespace: blog-dev
