---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: blog-app-credentials
  namespace: blog-prod
spec:
  encryptedData:
    password: AgAAAFZEc4DOuQNDExyt+H7AIwzGFdaEJtfXqLeUw3bdSi2YH8R1s/2zkh3NUnmH2wjkT+0L1jQUGMcf9/qHiiQzcANzi52nPkeKrj1Cg5lvFD+aG3dVTGk9qe0ZTMPV4sv6kUJEMH9wn8/2OwYNJSpTWCKiQopeoFFYMmBwii0ZMJsWyDa5AlaehFHbbmUC5K9J0SPFcDe3u7R/8HxtCB4k642U7oo04RXiL6Q+VOpZNugJ5Hs2hwXzcQFpzbNNTxHtS25qIEcCiRUuUczwKQo81GPQOlv5Vjm9t3QYWF0+j4jCAXl7gnU8ZL8oVfBDrFdrDfbUqMTGdw23iP29XsqDiTZ+w4JRW19tOyst071c/8N8HDRIRMwJgtgyIDWp6/PxoXuOe+6Se+hqCt0Nsy6veNu7jqF4n42TKz8N379HVeiYGT7Dp4FX6nnkkr+0jpSBT8jLPOf1fpVU2dLcaGtCRYrwI2VTYSls5mkqdH97whQ7SfeHXUn8fkfvGx0coLvg+bYoYbyyrcxedfZY2ByuwYob5XC+kFE2jx5ankmkodBkmHSWJlDc1j5YOnjvxSaw/iXW64U8eym/jRRzog0GlTgvFGty5aOmHLQKAQmF4LLN6PIEBzFoGpUnHhcDHIGlQy9QUU5micbY8A0dTZM02vHGVnGSMhH0zHm0id/SdxYJfAkcRMZN0REwhabQK+jX0wz/vr/qJd++jvPHYE/Dx6XbdEoGVK6HMS5s7Zp3qQ==
  template:
    metadata:
      name: blog-app-credentials
      namespace: blog-prod
