---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nexus-registry
  namespace: blog-prod
spec:
  encryptedData:
    .dockerconfigjson: AgAcdn874a5ViV8YhsueiJ5Bz5GO2Q8VKrSv2ssx18xaJ7UWM0x3hZ+OZQ4MWmetXP16eBjdhLlb6ydnKoh3ac0a1NFAlwIpMZKBqwGDyj9fDiXech2DEsSeNdGX2kn3q/Q6LAq0RKiNhQnRX0PbjbkoFmStgWZcTebt0Fl0v2uPPS4J0ndqHvgwsErx3V5ivfypgnZgMmT/btv1eMSuWA4aVFZEfC6dzOGKHlnBix2L7O89eNzjN7IFo0qizIhs628s/hg/Y+4BYHUxB/4hOI86oVPrsYqbr1FiDvv+g2l1XZK02o+5Isxhd6AGpVjXPPO1FxBUrGDMUKnlXxLyZDPuWdZ8yz6O6nxAI/UygXKyvuKPqqPYZ9wwfCvSR0xdg9E2OLLTDenj+s55ieczEaRhwU9ZYYE71nLMuGDK+Hldvn55hnjd+mmuz62r5fVv6jbXjitcq6LshienfQu/zZWGfv1Mo3M0fXg7sk6PkMbhLCYL9Om47m3RUDjnyxXYVHLTpI8s3tX2an27zPu66Z7PMoSW8viXNkxoRsg2CNab7yzUJYrmW3LT02h0RpGz1Rd8IohFCL4CMTljw4osTtxL8O/u6jNM/3bHB5wUxlc/jnOb4FngsuRPFFihaRichXc/cQj2WrwEnaZweNEabzbcqUAKOihbLrb7mPFIqZAgtLs/v7LXAs/kz8skO6OmuSLhv8gDUTVn+pjYu6kGoE6tBUHck/T7GNPose8BlqWP42dYmsSyw3/iGB/93ItfLL6Iz9UH0mpkBmXpPSqc7Op2kcc4E4pjm/lj75UgizxCNSe6HydfoQrtRNy0Sa1F+HDjUftRnZ3avi9yVVbIISAjjTSZuHOA8JQI5FSnM04KIxk29KKaS1aBCU2GDrBfdB1IvFKDf5awJwW7+jZr70KZOpYPgs3kCO4NdtyRGAJ/ulEt9c6+w5r/BdrfAdgNmYDhivbeUa+J4dgj+dQERIp1K12aqAyJgr1RpC8ijxobbwl16K92Fvu7pnhZtUwxzOkGJOWcf829iinx9KOf/1qWzAfuepoU0tRuJ6tm7AusV/0Q643TuEe5sRfd/U3LeqGOhVOHMP0IoMyQkwjX0K8tJJxyoC35
  template:
    metadata:
      labels:
        environment: prod
      name: nexus-registry
      namespace: blog-prod
    type: kubernetes.io/dockerconfigjson
