---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: blog-prod
spec:
  encryptedData:
    password: AgCXwJgouQ0Ii92FapzeuQPRsO4gWEBqoEETVwiHtimeboe3IOWchHiNZpgIUnC8MUzt1mRMOQ4LgHCG1luxKFY48Az0SMREPG3YE2vaYD5x2wGHNKJkdMwqBwew/320yuZYknEcmus5r6eagXLFKWgWXB3oLxU0AVGZ1EP6dqk3dFfZb/FqWJvn/rw70kI+Kt02xVifMHNEwDHMANJ4p1eaLXYTvf5fJgNHQjDLyu0/0YdzgwwGfy2uSviO/BXfNneniZ2IaLVqc6pG+baWwvsh5zCMMMNs9TUu2qiCoLxy0sKznOW07yZM+qi9Oy31WtEtjwZ73JMoZkqUmCI6Ybm9sTW5UB5zAwgu7fiaHcqzgwVXFxxyQLG5xGmYPyGUAy4OHc78uScMj0T9w8riPtjJYnmtz3kbL1/W1YFLp2yZ+q99xKAKxE15CCjXq0LyQrUu0UYk3dqlHF4CHBuNm5eFpxeGQycE7q/OKZmcEL8D1eWMKkHVXlRjmNw1/570MKDtXSF8zKX/PIPS7q0KP+I3Trb/Lh6T3pp81b0gMRR5yzui8Po7a28bzDpxIUoxdwPAZEXhgp+Eifi5GZjxADHF9lXRz6/SrmjptogP0WRLWCBbjACXCiOLpONaCJJrqeV5pvJvG6tguO4E8v8EbKBlMyJ2ovq9vgnYOvJ2G6djyQ7GI5f4FRBDZMIhoBzCNv5yOIgbg9BQb/HPNew3qbfE96avln42Zc43tZMqkzY3ZGTzE8Bi7pHjqJ6FVg==
  template:
    metadata:
      name: postgres-credentials
      namespace: blog-prod
