apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-media-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti
  selector:
    matchLabels:
      type: nfs
