---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: admin-credentials
  namespace: blog-stage
spec:
  encryptedData:
    ADMIN_PASSWORD: AgA1cYwg0zRQFh4vO5kqKkIDZuP2zTkszzoDRTtU8ApVf8++yim4S0mb2NVKfP9QMir9jh8Ip5JeTeFJtoe4EtQjMAolNkemHtuf/SBB0XQV0L/xo/VkTK2S/jDFdnQV2v32ZmP9Kzhf0Yzd0JwckaWsxlh7GAhrhHbxlF0EIMqOYzserD7+Q53YmDd9Wxkc5qhfZkrnQtSnAU8mlqS2NUTihoDKvNYNPt876C8m/x3LI+eXm+bt73c9gXaQC4+d5uZpy3F7IqIhYKFE1+/p0/zqKZOVk/5aHE7Pd4lVkdgClRgMP5uWONuVvKmvAlj7aKswtRjZtaTMynBgCMWdKn8ZOwc5OTc2EB6Z+6gTPGNy3odJXAA/LtUYw9YyzSriYcFgXWvIyGPpHlJZ4BAlX0nx+Aj53Ky+tUJI2HyGoik+K/D3yo0uD/0Xz3wQgXrl722YLXfeBWvH3taRKzs8eoZtFSQ42H3TWL78kcRerU/1IT8KGldQJU/UIwXXrjaa2f0reqnZb1cKtmXJnzgmX0EtPYCw6gztckdTGa/apbuY0QLsInCdfyo+cCnmwazXHwEYjKyOGRQcV7MuaN9K9qmzgwkaSFd8eg9neXeCCAojOx1bx8Uh4zXc2v/saboX3TH2Vf2ByNBkSICk/ObFs5V1SlhtP9ozlM0A2kpr4cytNiYYxEllhaGoNQyRhelEbS9lPEZAeAF1f7f7N6twzFMwzfWQsbz7sJOFIbfuLdPLHQ==
    ADMIN_USERNAME: AgAo71t7jvu7PntkqH7a5tAFSS4555qudSV+nM7Eq/1SZQ8FXm+m4YxhEAfmYhjXeilspME8/ZbxG+Ww+9GGS61DOnSLs/2JFwHW/iFh9Pty3pYJruzoPn9/0pnn3U8tpzqfRe54A1WnaiAEbZ5lMKqoc2SLOtTrhqGNQXF14oJkjBcBNGg+KiVut/AnsM9P3poK0X754s1Psd/k0lgTVY0xu/9Jz7e2NtdrWpzwd660rWHyN3m1kkH/ksZr6sd3E//NcGFhYSSA7MAkPaHOxiPZl6aW4sNte8gu8SyqK0Mcr1Op3VGoyBWlx8IKmJmCaaK41E4RaM3eome7WJRXa4vF4jAnVARHdwQ30xAVPc+I9bYFTtqx5s5YyyiYP1TAAlj3sVjKukGnNEBGF81F80GMjZv2X/AFsXBfe+cNJVfu1Q8vh1x6Zy219Sl3mzov7Mh6znM8O4u1ld7kn9Vxqhgj5fM3lbfYBlHEMWHkwlgnO0IrggIlaU0ekV1vy8kEJqoFr8E/UxBtdtfdvbnoaROqNtHQTlLZmvlHIQfv9ZLiwxzkh8CCsI49tAPgQ4Z0xyDdpFFF1AtRijd0cwtuP//GFO0vYZfgDQW+JqkHtVBOOxoMTjeyeivUb5AerxfyO8zueKEXG+Gi3YkLVeYbOn+r5S0vgUnu4A+lSwSfuPyykbW397tGka9kuEa4izlqepWPhlqMYQ==
  template:
    metadata:
      name: admin-credentials
      namespace: blog-stage
