---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: admin-credentials
  namespace: blog-stage
spec:
  encryptedData:
    ADMIN_PASSWORD: AgARITQCmlfI1vhhl1LuhG7YM3xDVKKOAyob4KHSZDPqLfoeeRNqWlQjoM2vkNCmjGx01GPfegB0HxuQS30EYiE0n4Ja21Jz/IhxKjj4jYqVAhn6bYXnLfDA9ui1dQQOKK85riz1e79TKXNhyMLbYsA6ftb0F0OtkBHaTaVXBuvs3Aypiuv95tjy1wXr3pNo4PluPV0FMb7Nr6ddEBSyS6jtPYrFW7kZTBtlcf/793p20+jRl27XYzhxWU2xLy8dPUMme+UKloqGH2LmkreFkesHdYzXQR+3/9ZVCFaXQwX6XO49Y21u49qvcZHt9ojG6PSwFMF566W6okTmZeCxgFN9WbWNeqgdsCQB1Q/6PgVPtXuvkoyS3xoTOUoJdv4QTVeuS1NoBJ9QhJslla4p7MNm2ZPBKYnk50XidJTNj+cBeywlLId7QipKD8FALc+RJW8QOSqQJ3DqW+YRB6F+3ynG+CQYZzXLHyRA0vaIzUt6H/kIMigArsKQb0OvWbfCiIZw1R0m05oXZsNyW28M/mjTvXj2yA6RrmYsNr1ID8KzkFnsVJY3JAEOvgsyt0euXmEfoF2MFQE3YMhZeWUK1P2RXNWQvx8mmhJ+wcL/5/NZQ/Q8tUlaRGRA1uds35LqdhY5L6sAOMJplc2zynrC2Nl3SCNdno1qpMWl6uA6M7dfGQ1mci/tczEvg8SkFR7fuysog0dT7VgP5PgUKbiASADhIDmnTLozq199ZC76r1SPQw==
    ADMIN_USERNAME: AgArPe1kbuqIq5uwSLhqge5GZ5uGFHIkSTyOAg7kl3FP3YNlO37D7zY9MRh8kAUvs9O3qgMV3grmlaaKe6HN40TUJECS0v6PEoXuNFwyMEiibKm4qD2ugD6xOORJ76J7Dtedt2XAg8c6/b7UjvKpk1STU3JorWx0zquxkC7QuNltpYRUww2Bf74lirFYBbEpggvLq3aNhoXaznFqI+bBEvZAqFkRxYEJFo4y6dhwtxtppb3kToe4l7U0PrYI25WNzK3oxIF4fn88XpTYyo0VFsb/o8k0J6Lyx+bGhE1E7ekxvYJwdQd06kaQie1G7XK/HtXjckIkTFh9Qc+PDvsfOFLQS72FDSZThMwZ9kMsGVhZPXG9HRqtRDvqcm2Mq1b0GKDLkuOpjCkPc+L4Ftw1/OzwVMLUL37BIoWS/987iYVevxGqIc/4FnSTKCHEfvaFLED4hX3VOE80S9gILMo7RTA84nnI6WXqAGG7cW5NVrQ0RTPCl3G8+LuxeckWe+zuT2rvN76NmjQOYQbnhlggkCs6yyPGvaiJ6aSkxVJANFSPXnNGephTP0ltk4qL8gHj+lv9jkGSyiNtdImhyFaEzqCVLagEFNRwOXL2QKKFeJ+mmghCOObHUXKWABvIQjOl6UpCTV1W3zn7uQG+IOUbyupHm58DsIAXEU5SJAB8XzbijgRtUGVRnsix7VHvO3X6aqtPLdAiIA==
  template:
    metadata:
      name: admin-credentials
      namespace: blog-stage
