---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: admin-credentials
  namespace: blog-stage
spec:
  encryptedData:
    ADMIN_PASSWORD: AgCYMHBUbkxLai/Fx2IN2hjk8//XlyC9pH+Nh75eZcptwGlA+OrsUbDeCRo85wl3sXMSvf1BEw124NzpsgjAKv8gL0BHMxj0DGG/E47mp28F3ziayHlh1UcKJpOjvMoVopipPlTnRb4AaVlDLKH37wQTbT5aq8znKaoEv7S+3eaUiDf/pS8CAWT0n2+kMaKS6esYjbFdHE6D7/WspMudlBsN/0tJDdWIz4NR+eWsD3U0mS0ySWmieE4SOTxtFC41qmrQUEoZKcgioNK1fytNWGYgiSZs5mqpg33xTvWafDoJhCgR/zkUvrLfbSqa7bGJYeXbbNoJojni9Ph7JgfEOg7Yk4dwqSMEPXyrdmLUks2TkdoezO4yTvj602hJdgIdOoNGj+9jSqCdqy1yjiCw1VXfqwFtKOPvtitRHPByVBFFGgB2EmO5Y/oafzwGJSpZtxisaR14DsvwK++1G87oTgHngdzQYEOVQxBCxy2kJhCFoRvRPe5bCh/XgUanr8mCv4NqZUqvgHMfQVPG+p9+LXeaXxT8y649Eiq5vJy0MgOggbeVM4ynDb50YiwmG12TMlPwJTHGd8PKoQsS9E1kRFGGGqdR30kIPRPDhMTLmPhRK5e6L5+LxI3fajsEcrSiwxhTTozJDcclT+RIQ5qwsIJIpYKlP1wzc4tS7aXXWpjaY1FxpItaElP4nI6Wwd0w9wO/gFyRoIPDELwRzmW52SZtdQ4B6gZ7JFti119FbwiSGubzV0D0GbTNN2qYvQ==
    ADMIN_USERNAME: AgAzMRzhn3qSD18yBA8Og93y7POTuREzm2MEsbhwNQHkQmlHExFW69Cetc/eyZJcb6CwD8Q0xrlKrNLoG8RN6IwPWoDyHMz9zsn1LZWckH29W4V/bdXgGhxYyah/uL7xyBTPWzsv6XepNL4IagfYiIouNbrszWiZcxxaRYyf7YS2r9qajyKJ2N9ZsCwwdo+adebwvOmN/fz+CAT5ed2x9Udul70OxhlLzMvsLxbGW7ZE2oCsElXBoDJNAYOHHZj1I7jrm0ipPnJChAmtFVRVsfC/HAPsrSgnagx/hbQRIlaOH0pAOJ8nsjY6UwefRGcVpOn+8muGRb4fArQOESygDSiNXZdJWpUHso3D5h0wNTTlCngvN/9U7HU08dbHzqVd6826AoXq0jQZG6XvtQSEYYBkXezWDkcH9vXR11V67bfp/w3UZI/iFXMIInbfE0n1OjxE8MEyXqDbWNIUG38znb0pLU66c3sELRz3G+GePVpClMZKAOW286dDbWrCG0lgppUVT/9W1yeefAphX01IR962tsu7q2i2JPENzXpcPoMnRYl/ud16w4q7d99CRdgVbBTZxx9UoDImYz9KT6fKw4/hxcSEpV3YuBeyUdAkCfBs/l9Wl4Xw/c6rtKbeAK2WS+VwzeCROjpYr50grzsNUW07FaxuAEOFt0m/u7q9K2OYybflxhbYoKq8wLF1VH3fINt77lbQpA==
  template:
    metadata:
      name: admin-credentials
      namespace: blog-stage
