---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: blog-app-credentials
  namespace: blog-stage
spec:
  encryptedData:
    password: AgCydIztcBZwE5YK969bKcMhUix0KwQDkv2iLoJVAe9SN34q0zoKhxIUDfR7oSb3rTWuyo9WLF5clLhExIwjSPS3f5T2Jlp8RJAmSAHxgZpFqUm2etRBNI/66bShDVQE4W1JDRHxbdF4fe2kYWPcUVq+aGx/4GoTzq9VKW5rv6QNbDLQ/MHoJo6ZVfQ+2I3X8lTAt/eAXIiBKDrfGSZbO2khUXitvAGmTZAAHHT5E4bQ+8gw5Px18zReefdjSYgdYcCDv6H+6q83tjuRFj+jvFA/s2XAwHjV2rrgE20c/269tYNWef5SVd51ZhbeBmHg8X0Pwt1F7HUGPavropPD5m46TZ3tHOYkDRtT4eP2XauLPcXGyZh10Us/YmufB3EwVRqSjWO/7xScI7i/PYFGwFXCNfkvrfmG2wEYp30mxfVwASWE2QSaU9zInsgJvdgXKZ9Xbqwv/rCYAeW0VkTHLCljXEg0jxJCr5YPvVuvX+D/xyvxBUOeQrU6fNneR/DgpFCxpHQo0z2gycGZwtqdzexofoF7lZInCoR3BPrmZZaIDWlHRpmsD0UDqeNlDZRZYjjVM3rT5KA636jz6HqGwZvsah4h4tSGbEpUV59XfFzKnrljC1NMB/qeQXACgLXVO8+oI6V6Es1Mk/Olv4H996302TycUYBlNS/dQIT/rNcoo/m/LAwYswQGl21NryZLuZ0G2jHe60bZQTxDIg8U1pwHk7jJqpZavgWm+U3V1vjR9A==
  template:
    metadata:
      name: blog-app-credentials
      namespace: blog-stage
