---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-secret
  namespace: blog-stage
spec:
  encryptedData:
    JWT_SECRET: AgAHLryT8K4afGEsYZC2a3Dhl82z0tThyjZVxLWrjL+xlrb0/MfDY8t8sIM06hIy/QjH6qrZp4zvMwHJeppi4K8Fmqu+84GW5BNeq8EnIPfOmLehHrjnkY/2XsnURC0bO/2Kzr5cD7py51qF8OKqGWro1eE5grUZHq9XBE2rA5QvmkrEFDb3dZGgZYFvgtCG7q1j12eI8S4xWB78T7Etkmilm5tuIGEtizFvTuOflHb/MJcD75w51xSRZu391L2p8QSVAYBtY6cIHl7YK8FHStfAZxqICHI7T9zmB2gKAKUff++G1haL9ixa7IQaADgxG2AIGJ5O43tHk0Ehj3WX3azzEAktnEo3izSnddFTjF6MbbnJ/rw+NbFV14HKe1WYINvjczIxf+375ABRB8F5axOaENuJuz0keG/M6Jxro6uOq3W0q1xW8oGh6z31jw6Wu12fz+ciQDJSrQdXeuXKWJMpOmm2skDBHKh+U9t13KfWRIlmrbmGz3+QGETJc05/e5kNmigQhkUjHWHiqMj2+lwBIEm6u7POXxfnKRxGNECQMJ0pcgTb47WmrqznH6/sTeduDkMRf/+OCCgiB13u143SQS1yxZExTLkpICsSKzkDUnkVRbNu1hZuqTaxlUOPjZ6Ib4OtA3/KmMw9BdlMnocby9g7fn0Zu6PYMMHHrBnuZGCXlSN+9UHGeJi87hU/8dpGvR9+pf4E8YJ6g3lREOSBjTBH9hpJsAJh4eMB7GXAsrRUutzkrp04v5sluFF04nZpR1EtBM0QgAKpY/OKw03U
  template:
    metadata:
      name: jwt-secret
      namespace: blog-stage
