---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-secret
  namespace: blog-stage
spec:
  encryptedData:
    JWT_SECRET: AgAAooFT9enxg3wBCEGL5wgO3DQO7UYwuRscZHVjoRSvd1xyoMfpg/I35wE7b0AabGKButgvWvo6nnU+4tUU445+d7IFH0+f7Vz+QJqbpYqwRM/bmsFfKm6N2fe+JWLLJOd0f1PRCwGg9bf1aCUhw9kb/EqrxrDXqeaj1AXrTOwNC8OwucH6co6SmMsAUo+Bay/dhcG+sVXd9UiHzrR4fmkML1XjA5plf/13uH8FFRCEylDB34hRtYrxRYHGmXHrsNEfaL1V1VOxCS4QRMAXQlIolVIEbSvAYzG4HhEKu94XM5MsoHQ8XinZeexU0IE3gPt2HsM7O13sOE+T0xx8djBvofh75ib9naermREzt8br75EAYI0txK6+QnjIyN8Exc8IdMQ3Ox1oJ5mf6Pi/GT8PfuHzi0xLizOJ9GArYcL5zr4tzadXyCU6vRNvPfJ15ctczrpE5ZDEA9YwrYDx+QqXr+Z5gj/0zivM0ur5GBIePK+kUtjY9G2ETv11uwKfWxMdxbpzg6XF2YzWNwY4dZQK6Do+4j0mEEvassjLKWJ8FQroYejqO4p/6O7UR+LmiyLQUryVlI4YmuRF+3rcz3PdRCCn1GS9qw2ISiOXYrmRR4d6aqudvu9MhJL8lAjS+BqxNFh9+CWMOdDVd/V3hz7G7PO103tlfl9fIySLs6N6mqk0eqoxF9L0vi2Q+fG3rLFT9QQ4puxElbVpVn2V/CYSXeOclNDV5D7jOqknjygEJzxKbq4buOM/+0iqNdhw+zQ3WtWut/dwV9aO4Ao61UzO
  template:
    metadata:
      name: jwt-secret
      namespace: blog-stage
