---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: blog-stage
spec:
  encryptedData:
    password: AgBkWUTiN2ydMpKhNpLdmCA0FTFx23gEkJVghIG7kH101TXpHVbBy6UtccCDlYKLhvFKo3/MB8BQibahv6PXPnZ2W84Rl7mZwcyBmysl4Z/eqYIDMXqSgcbBo+wfm1WyNzehK1KpY+Sr8do5CL2VIXcEgq1ofULiyrDVPCwNNOJBty4JM9uS7yoBJzg11NNEFVlAUeRBGsN/1uVHx+K0BSxjQNXaXZZzr0GU8ZtJH3Forbc3u9HQ9lXKJ/hRYocE27RDis+l9HfQdX2dXnv4hdN8ttNddtpBKK1y+AAQ94MpvHEvgR4VkW0e5+RcZoVAmBuURlfOU92JRwHO1X/bVSCxBr49qcmM6/6u2fn7mboQiGxFr36bV4LK4q/RF0HTLaKDawT9qihvHmIXYRGGsaFc85haOmU4jk+Puq6LCkafY6AMfgd2TIedS3kqxGoWZvrFX76uLpkjgwSQSt2JzDw1830ZSWJVQ/fT2yzNokkKaf/exSFDl4fH4Uo4+a3pj2Xyx64ASSiY+q8/57WFagMAYU1gv78onxWN3SLDWU+qD0wKLZ6GniqfbJqtnFx2/0J1IX8Y5zLdThzbM1ulhs1c/ayl+FYpr6kDmFnaNS9sORkIgpzx/od6AooHcy3f1QDVPUeD5Qa2FAiCe8MsrGeFMFycQ438PYLyybBH2OnK/N9uCTC9W0haTfsQ0oEbjaL9iLOHZ3vjsuShv1dSJbTfLrS6D8Pdgqt/ADIDQGF6jLPohcotfIt2BUDqig==
  template:
    metadata:
      name: postgres-credentials
      namespace: blog-stage
