---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: blog-stage
spec:
  encryptedData:
    password: AgCDjLtiaOG1a/QyNUK57qymGyO+9s7tN5Na4gEid0cfZutchwiODJ1onbnB2nZGLeGe9ctyTZjEMRZlEA5U79R6OO0VuzpbNaYN7OEtsJbVZLv3e4LbPK0XpM/Dbyglg2agnmJ5rzSqedOVbLMTHfbjTXuAAec36mf0mybceUuHs/trjsiMyjgLlWsv7B71zXOWnPw+ea/0AgOM7AOa/8uhfyCzLmYgwFEBUPA+FLMO+di6NFuPJGzTskWRAL0f6rAvTjqNjQ2hh95Kns1wk2bnWAb1b/dvzLkq6S69ZbIkm7DcWvIzGlvP28M5LF4fHzHw9dI/CwkzzVpUoatDxNmxX04PmYxj1gAQZ6cKr2/jviwmhk5WQAhT1ziCOnvYBhU4ogL+XnqqstRALf/cPzstjRD9Tg10jns+bEf469LqplqQYZkFoKS785EVktoDhn1X1F/WqJd/xfFj7+BVZ5JWoPzEFaAUn01UZtSTXPTqNdkHhactcGsqP3M4A7wD+u3n7Sn8jxgebFsdokzuWtcmgf5i9yEc4NKtc/nXmDbIWnLvJKH1tWegz3vZhNxPaXIPaFhoWOZ7f5zyj15abaWBhuGuscSnbEkVFKXgNYApic4pxem13Z6c5lxQmI4PMiWvmd+aJjhtlT5qc8mN7gy9rMh+FBNQ177Ib4tNkdSrGV+BbGDDt+ikSaurvhKV4CqMlhI/te8svBTsdXbK/+pR95EFrdlouszQ6hDecbILmtwAdfpNbmlyPXPQlA==
  template:
    metadata:
      name: postgres-credentials
      namespace: blog-stage
