apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-ui
spec:
  template:
    spec:
      containers:
      - name: blog-ui
        image: docker.pdlab.dev/blog-ui:develop-latest
        imagePullPolicy: Always
