apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-api
spec:
  template:
    spec:
      containers:
      - name: blog-api
        image: docker.toastedbytes.com/blog-api:develop-latest
        imagePullPolicy: Always
        env:
        - name: APP_ENVIRONMENT
          value: "prod"
