apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.11.0
    chart: argocd-image-updater
    helm:
      valuesObject:
        config:
          registries:
            - name: Nexus Docker Registry
              prefix: docker.toastedbytes.com
              api_url: https://docker.toastedbytes.com
              credentials: secret:argocd/nexus-registry-creds#creds
              default: true
          logLevel: info
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
