---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: admin-credentials
  namespace: blog-dev
spec:
  encryptedData:
    ADMIN_PASSWORD: AgBmZPI7A5ocMuAbBkONeDJI6xkNNsJdZoeiBESBPH7Bm9Me7cpoa6l1b5bkPvrxo3eYvI0UgRubVUFGfsgduOuOjQQf/ANlLataUnCKFXQa9Dn6aXo9wEew4tzhDCcTwMKjlu313igTaK+lm21lxtrUFtXnxfWqLeSzFK+xQMIlF/tEt2Ffv9W4df/D9JQCzDdyBSf878ntyO5twHncp9gn+zL1HKIVMVqDJiO4EjNxFWXPvJ/bm8jDmFUceixxKKhyo2mqeUclkD+tlMHXM1Ipmi+w5qhgw8qgS26D+fE8vUwLZbfOpAlFcfTTY+I03M47HCyT1XAWHQoJ2xFuzdrK+oGbiy3RVO6PsbT4fsdS3Kyxcf76QyoXtSzDF1z5FXt+7YnSFMUdMVKuEom7xHnIZxR6b2dmWCKLAzuk+cT0UjH1RKhJYo6GmQ75CduqQhBxyByspz489lDmFsURR6X571eNf51tQdseSbatvyyu9LXnOgCDEGNSsZP1gaIQkPFkLg7tMFuJIOFKLY2HQOBKo1CgutKVYc0LMFxCoVBEIVoEUIZBNuZU0tyNnUFZGmmOap0uUhMZ9Zqiy2aj04jI+bD0eZnEIWut1uX9yg3KenzakfAkmcc9Pg5jcM9gKsjsgSliixzXU0QEYpJ85uDyZOPnvSWnWzELqVU0LmyHXQDBbiUuNU9Yq8NgjMDtEfxQvG3XSdUG1NcftNfeMqPP4o8XBdn0VOk=
    ADMIN_USERNAME: AgAMQSaHya6TLZwdCNyP8jUtFgVzEXFUH5wTQp2KpQqZXCSYYiIrzysMZmFk1zqLTDeqKRKN/5V7o3okkaPqvIawbfHx/Z5QAflxRa245pnUjDBBSVbam6A7Gxl5KgYl5d+NcpWDCdQu67YvOnAfMSZ9Ib0UttBwa/ub9Etpa08GUEdJo6vmCjaCSofWOHKAc7j50qItxFvCuxfIoV5BdeCQTmrn2BjM9T2Dc6L7I9Ghi5Pz3/eshgXSlhSp115eUJVLnIfKYGsYql+I81tkbTCXZGe0rW7k/LVUTGG19QUHVYXckBpXqnKDB+Tpvs++ZlpCVuOoTWZVJ4FoF14qiBPsouYREbSaf+1ccrPIKrASDB0k8p5zHXcaki38ZboksVFacEqhUKJVRW1MmCsPydV2PVTtPf86qR6cGM2Fomhthu9k3vVwNbZ5W2x6kDwr1wYHP2ax91rtQD8NZWMibijPXwkK+NSh7gr4+kaw7fZqMecMXJ0FQsi/REghIXNpqhScoPprbbIFd/MY84s8vr/EX3VWV0D4L3g0WF1cHlhLiMdjCWnnCnSyPxq0Z3M86WVJS17a1zSlTFszTbNEcFZy1C/+nW2v2n6oxRKCtN7XrXs7YN3aJaZqVvth7Ym4wwXT3JAGAjDbd07htPh+2dIcjmFgOUMJMpEe6nPeG4FoI1t9qf0Ykw4TPLPwXuXLgzM6Pl89Uw==
  template:
    metadata:
      name: admin-credentials
      namespace: blog-dev
    type: Opaque
