---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: blog-app-credentials
  namespace: blog-dev
spec:
  encryptedData:
    password: AgCFW5TL+qjjN3Q2T0ryYDC1kYGEKQZXM3ipn72C5puUvK5IM2QCmhEZpcnGUv5Gb4sL+wJmu1R3NW0aNiZS/GtOGmVIsOatcjbVq06WqXV4yskfABcj8Vaujt/zEgt5570xbrJquWW7X2/Q+pmsk8cLUiYRYXY94I94tkBgaREjEOv8Fwbh73HVWnHDb/AmOEKqtWIoqVHu0576iu9A4i60nPDtR9GafQxMg0BAtaCxSs2RxRZhmVxTVJzDt7VJ5QfVe9EADQsQrl4OHDxorWVoyThxIo3+wfAjjkvJgI0ai07Q4ndFtd1O3HVAHrUs8gi+gxzaOZPMgxTdYlO2bWFCb9DjGP6/A/CYxecz43RGxyzXKtTTI6a/RZ8qBTCnuDmYuHn3xNhfFjVEXnwudUuVcfHnasEQEyMB/pamAoCP0eWwq5vwYSIVQsZiLBC9Id+9jgzgfhCnlp36YNwirx+5BJyrUZ/n3S/qwWLYPO9vXsNVL36craYjzyAQlgWL0Cy/vaKF3UV0Cy+ZleIwQS0KRImW9aGfpjc1yZ3HleEycexkOuBnrXKaSdnSlOe1h7G+aq5egegExNUNxek1doDUXj8dzF2Clg/fpviZUyxZUta0LSn0IOTUEEzvtBqwiw1u3gDO41/3EglAKynS4fN9bLuxnERjN6OCipjBSbpKt2XIWDSeRPTQ0myz5yARR3IYcYUXPUxymuQTnRggrfiqmPZRNKZDT6wq3Di5LWdutS4GvtU4Ey3SW3Hd0Q==
  template:
    metadata:
      name: blog-app-credentials
      namespace: blog-dev
