---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-secret
  namespace: dev
spec:
  encryptedData:
    secret: AgAJ4nSsSsORCX65ijoo8FyL3wCnpKOgWo3E9abgjm1q5VUaCWP3+6Jbw5xGyiqjEZoD3Vq0rHr+yOuodWy46otuQz8d2niDqKIc760jZiJ5Td/JnJzj7sVBeBXQxv/5uRwn2ykB2OT646Lc+2geV9LXG/z1DPVrR7MOhu3m4L8MqpEaO89lIGOX18ZCZBK4i914B2xdBJoFKg7qHssKpMXQ/+CP3SjRVqU4k/talPXsMhOEFus4hmpQ+wWnMTjiwXfA2e84MEvk1Q+JORsTNQ1abCB/vmImsvgv3ZQ/UYdVgEp/hbUPGwTe0ErM1jWPGaTiSDg3JMVWT2GnElxEvJyaFKGKHqAmn4bmagG1ec8ah3rsCHNRiNs2cOmzA/PDDi7XCmIoRjvm+KxCe5Oci3PueLvXj+T2DErSeU6p/2NJVEfBKwzxCFmQbFMMKhdB3rOd5e8CSVFDNU96AxP+oETDHH9eapAfriuCSnmkv1PxC+nkPnUGq2NyT2JkfvZufnfQ0C4ljaYtmB3yMnDvCfpRUdE0HMLLWjIg93ToB5C3/7XSkF9YtQeTiTQlc8cVli6xOXdVzp8HWGucoG7XUo7hffVmgCD5JE39GLk+dUAtJkEbnSJJM3OvN9EFxWa0oouI+Kfo/RiN9UZTre4POz3G/GLxeoGgPvcRg6vpIdH8MWuYxrvAOq8+cAbH2Qyb3kDhEKxsrL3gjYgpLKFy2JdL+7pCnJJN5Wp/Q4G3mvNz/8z62qasp9yv7sevcfOxiijt3usDFQFbVrCvhqDw6xLzmKLpWC4ldqfCG3IdWbROSQJmbpiA4TBY
  template:
    metadata:
      name: jwt-secret
      namespace: dev
