---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nexus-registry
  namespace: dev
spec:
  encryptedData:
    .dockerconfigjson: AgBTOiA3vZ9PhLB2/5jdqr+vDozQ+1ajYMFw/YGCGjk1dIlHQGuA1xHySivoCsD5qJo3MLcr3g949tBkBhAmSwCDebHus1zlpEz4wJgxSWoi2Xq+uC7K1CcwVpcV5mkad9cYJSXcefzQN5dezkf8ybvDFWUB59AjbB3Z5U38+Q1l8Khr3z6DKaK2Uib7fA3YeoKIjj1JNOFesR9gvkpt8Syx+S0WzUbFxzvNvEIItG3D7625PMMpCORGuZxqWcDQUhAEVwQDIo5cEbjpbrWYi+aFMJH/HkmC3yV5XKWliPqMwF1CZ1+D5DqKy/T/oiOu7CxRmkuql9isHiheGO7R5fjLCewy3Vu9Y4TfWbVVk60EF3sDXXCV0DsJGsheBiDe3AbjN9d0Bcjrrx51oqPuk0B5GZ7Hs6S8wXWeFG3B80VJcImTNjeWDLqsx5VrR4y7NG4mlfl9sMsnx3jbVlZL5bVvqA6HRDIJJal7v2G0iZlp9ttFp4/Ds3YEnJOeJ7s6jJa8kRfw+iGZHbXnHybtskfG28DN0OxcG0h7BJ4YegSU6Ek3Nt9LUo7r2MFNdMiAUs8HGuBrx0+rxoL1VtRzdcMlgSoqWtZNMoNSTruQBBZmIPTEzSaqUnsU9Mp9I/FIFabd6ztLMbRTpLBwrn2e/5i8PgU1f9zv8uSGIKXxuOsffHqvbnpyl2azKVUPiQxtBNLs0fxh8j8ew5okl/O/WpNf9x29RA1PcXWEO3JTmk9HnZ0m49jbOK7ThfMjb//GnVMeW5Yib2eyWquKObpA2yWznltq4Tv7YNmtkMdl09AcHgL5v1dDl7ZcEFzghPKVTAtyt1DU3y7w8Mlp99r9awzx192YZ3NJ4e2wd3fBGOR6BB90Y/nKO1JcAoAzvwHK/lh3RM6+KIAvlTIU4LXkdZPBs7fdqCwj+iym4fU=
  template:
    metadata:
      name: nexus-registry
      namespace: dev
    type: kubernetes.io/dockerconfigjson
