---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: dev
spec:
  encryptedData:
    password: AgB9zlWfwR/2A09LH+ILspyJonJEH62/BYJ9so2Yayx8CSnZOA8QDXUI/VX7CK0ATytowwEUOnPgSN2mst9tPKyJP37VKfbiwhMjpfnJF2jqxrajPpEBf2h9b4nA3i/Uf93tHXFGoLrxdQwb3D0WZxPEQnGI82w0UJSP1ETtERf+F+MOvfFYNsH9ayQFdNFMTg2OB27WOkoNDDVChzIFp8rAYHhM1fP/GhEw5v5t0V+Hjt8a62/bmN16lujuSgmjLactQtPWsw5MNOECq4Wc1OCkyVzRGZsjS86h2wbU+DEIHWMErFt00eRe0bupkC6GklNNbTOnjBpBHrkcqb+V87jRugPUCK5xirUfNWED81o+E1gC66DRWIeML37f4zL1t3lHpvR2HQq3ODVkypQ/3YFekduCD7h0TzJjT/9ThY/3UtyhCUf4RMz7HOTa7hEFwc2pdFjR1FX0+vlSn8zEVH4IpyjPh18KJIy7c626Ih5/ILUhx2hsz9kKu3cfmLP1OsCE+BDhz5iBnpux+PPujpa5NqzMhHZnqGQt+0yPIf+32cR2ThJPcqQ44Mwl3do1GeyIt6+maJcpZhXp4orMSZRpPeh7TlmzdpNkbYhgMDn8ogm/5aV5Qy4Ia+DD9umrzMxZNgPqPFIFbWFeRTjkBGt6Xh34oXKnUEP9DHERwH17sB4PWk8wlo7wovQvLxLp62Nq8MLGHVPXswUiX79ZryjS/JF6Wd9Xll2e8vK5pcgnyvaEtabwlSW27X0Cww==
  template:
    metadata:
      name: postgres-credentials
      namespace: dev
