---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: dev
spec:
  encryptedData:
    password: AgCh8fyZsjYGmxYllBS1r8cI7w5V3kTkdeig+aFDUfp2LFuBrJAByY2TH4Wz+5k7qhG9KlM3CFkUTut+kkJsTVqyW0OPIELOTKpPRSrtuLRih0zSgS3sVZPVKjsP3BNfbnrEx2JPA7BFl10Myn2fGWnz9xjcVXZPaBYYE2GfdVD/E+xzIEyoMUHb47unJr/JT0laYT9LYL0/pSODNso3apnDKy5A7bWPpF103NzcM+3G35A470lxHpRbvEgMq2/T2OahDN32kd48+uaDWslerzIeX+h74sRMDeGIxg/q8LR4DPU7G5qPooI8hP/J9sXFOrcLxXX3GN7HytAB0N0XfV4KKkgo9765EXjY9Bk9JPBtZUN0dmvnt4B39nZzTflZeI0JkY2bq3/jvxQV+UvJKp26CsVtc0mylf4OQO+EWn0MCTRbD8Gk3JWJKvV7so/j/sZH2e824QdJoXkMwGLRX244gAwBiqgDYtETcUm8tdwUrWU1xBcwzJsOlphyMMc2U2CT7pO9JpI1f6OSn51dOWfrt8Vrx1kMC8v/K4V5+3SGIppjc4veqzBtJssY83ML3HtBac806WbxmHLxZ6OxNHpK5oqXsyvbJmxyc4Hh4roRqCHRnkM1mzeUm1K0Mrvdsrx6b8gfisCbYXND5oeBrfhCX9RrUTNGS+TqUsqOFI3KPspvlWVw8Enz2Ya/OM3MM4mkkocJl1qXgI529DITc3CoMNcIylIV/RqzoZ3HjAwJVSurrpEZRvlx9HytEQ==
  template:
    metadata:
      name: postgres-credentials
      namespace: dev
