---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-secret
  namespace: dev
spec:
  encryptedData:
    secret: AgBzGxanGwfwHS6Q/A9k6iE1l87ZqY2e5x3v3q3Tty4HjIjNjWYoLeXm+KqoaOqyS8HHjICNVK46EskeZ35Hs9ToDqsFaplX9Dq3pTKLVlcqfweb9wM8cHhP0/NXrL4Y6GB33abgLwx5bpBAJJ2ej5/5qWcHytw42ZW4yP5Ma8HOCAirQr78bODD1cDczpry6TOJNCAW5cYeEInkM+FQBw7qrWbYnzz+a38Iet26rYgcucHbPT/30sq6PZ42Br0KskOikeoPq/2QXcJgWJ3RO2OUfZ1eoUlPAJS+FNj/+M7pGg6/v1uvJ49lcATGrlaoXLF9No7agKncrrQzxW0ufAVD2R5ckUTi37pZPPqTog099R8TSJIJ9pDZY3P4jMUKpOCctGMWyB5mIuBkNbTCf29Iok3fNi3Tb2wRATvFR1UN4LufuWsesmV5ozMzvOioESXQORJOu7TCt6epB7qD91IYemeE9tVDrt7juZmW1EfqzX1Aos94N1WcYHotWxclcq3rRvLqJcXFcXFQujUG6NOVWTucfDxx/AilUXbMWfDHBMiZ06hy+lw69+qoBJVTv/We2BGOOtwRMeB8XD31WzQUowwYsvKLc+ulD0uMoeyrlznM+kzpQMO22WCl6ZUl4oiov08ilXHyLmTi6Zzmz43HQquvHqNHjQHg47uqZz2N0uNv3TxcvP6UUYlwjfpjMJq0xGoOO6w4LWD3E7t3rXEXebQRdmkWk2cZAV/wKymIv4FXjgCWOqIW3xtU2AFo0uxoENevdfB6aOnlcKFrIB6g1WqGG/viRQOW4ehDq8CY2oIVf/Jt0J+G
  template:
    metadata:
      name: jwt-secret
      namespace: dev
